default: build run clean_exe

build:	main.c io.c ui.c struct_functions.c base_functions.c
		gcc -g main.c io.c ui.c struct_functions.c base_functions.c -o clab7.exe

run:
	clab7.exe

clean_exe:
	del clab7.exe
	