build:
	g++ main.c doubly_linked_list.c m_number_io.c math_for_m_numbers.c tasks.c -o clab5.exe

run:
	clab5.exe

clean:
	del /f clab5.exe

lint:
	splint main.c doubly_linked_list.c m_number_io.c math_for_m_numbers.c tasks.c