default: build run clean_exe

build:
	gcc -g -Wall -Wno-unknown-pragmas -std=c89 main.c io.c proc.c ui.c structs_and_base_functions.c -o clab2.exe

run:
	clab2.exe

clean_exe:
	del clab2.exe

clean_txts:
	del *.txt
